import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Input } from '@/components/ui/input';
import { AlertTriangle, Menu, MessageCircle, Phone, ArrowRight, X, MoreHorizontal, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

const TalkToDelphiPage = () => {
    const navigate = useNavigate();
    const [isDescriptionExpanded, setIsDescriptionExpanded] = useState(true);
    const [message, setMessage] = useState('');
    const [isDisclaimerVisible, setIsDisclaimerVisible] = useState(true);

    return (
        <div className="min-h-screen bg-background flex flex-col">
            {/* Disclaimer Banner */}
            {isDisclaimerVisible && (
                <div className="bg-orange-50 px-4 py-2 text-center text-xs md:text-sm text-orange-800 flex items-center justify-center gap-2 relative">
                    <AlertTriangle className="w-4 h-4 text-orange-500" />
                    <span>This is an AI assistant based on Mitesh's teachings and content. Responses are generated by AI and do not replace personalized coaching or professional advice.</span>
                    <button
                        onClick={() => setIsDisclaimerVisible(false)}
                        className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                    >
                        <X className="w-4 h-4" />
                    </button>
                </div>
            )}

            {/* Header */}
            <header className="px-4 py-4 flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon">
                        <Menu className="w-6 h-6" />
                    </Button>
                    <div className="w-8 h-8 text-orange-500">
                        {/* Placeholder for the logo icon seen in screenshot */}
                        <svg viewBox="0 0 24 24" fill="currentColor" className="w-full h-full">
                            <path d="M12 2L2 7l10 5 10-5-10-5zm0 9l2.5-1.25L12 8.5l-2.5 1.25L12 11zm0 2.5l-5-2.5-5 2.5L12 22l10-8.5-5-2.5-5 2.5z" />
                        </svg>
                    </div>
                </div>
                <div className="flex items-center gap-4">
                    <div className="w-8 h-8 rounded-full bg-teal-500 text-white flex items-center justify-center text-sm font-medium">
                        K
                    </div>
                    <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
                        <X className="w-6 h-6" />
                    </Button>
                </div>
            </header>

            {/* Main Content */}
            <main className="flex-1 max-w-3xl mx-auto w-full px-4 py-8 flex flex-col items-center text-center space-y-8">

                {/* Profile Section */}
                <div className="space-y-4 w-full">
                    <div className="relative mx-auto w-24 h-24 md:w-32 md:h-32">
                        <Avatar className="w-full h-full border-4 border-white shadow-lg">
                            <AvatarImage src="https://miaoda-conversation-file.s3cdn.medo.dev/user-7nqges6yla0w/conv-81mqyjlan9xc/20251206/file-81ndgdtyydq8.png" alt="Mitesh Khatri" />
                            <AvatarFallback>MK</AvatarFallback>
                        </Avatar>
                        <div className="absolute top-0 right-0 md:-right-4">
                            <Button variant="ghost" size="icon" className="text-muted-foreground">
                                <MoreHorizontal className="w-5 h-5" />
                            </Button>
                        </div>
                    </div>

                    <div className="space-y-2">
                        <div className="flex items-center justify-center gap-2">
                            <h1 className="text-2xl font-bold">Mitesh Khatri</h1>
                            <img src="https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg" alt="Instagram" className="w-5 h-5" />
                        </div>
                        <p className="text-muted-foreground max-w-lg mx-auto">
                            Transformational Leadership Coach & Law of Attraction Expert Empowering Millions to Achieve Peak Success and Fulfillment
                        </p>
                        <p className="text-sm text-muted-foreground">+1 (888) 392-1561</p>
                    </div>

                    <div className="flex items-center justify-center gap-4 pt-2">
                        <Button
                            className="bg-orange-500 hover:bg-orange-600 text-white rounded-full px-8 gap-2"
                            onClick={() => navigate('/chat')}
                        >
                            <MessageCircle className="w-4 h-4" />
                            Chat
                        </Button>
                        <Button className="bg-orange-500 hover:bg-orange-600 text-white rounded-full px-8 gap-2">
                            <Phone className="w-4 h-4" />
                            Call
                        </Button>
                    </div>
                </div>

                {/* Description Section */}
                <div className="w-full text-left space-y-2 border-t pt-8">
                    <div className="flex items-center gap-2 text-lg font-semibold">
                        <Menu className="w-4 h-4 rotate-90" /> {/* Using Menu as a placeholder for the paragraph icon */}
                        <h2>Description</h2>
                    </div>
                    <div className="text-muted-foreground space-y-4 leading-relaxed">
                        <p>
                            Mitesh Khatri is a globally renowned leadership trainer, transformation coach, and bestselling author, known for his high-impact approach to personal and professional growth. As co-founder of Mitesh Khatri Training LLP with his wife Indu, he has trained over 350,000 individuals and partnered with 300+ Fortune 500 companies.
                        </p>
                        {isDescriptionExpanded && (
                            <>
                                <p>
                                    He specializes in powerful, experiential workshops using techniques like firewalking, NLP, and glasswalking to drive rapid mindset shifts and boost leadership, morale, and productivity. Mitesh is also a leading Law of Attraction coach, helping people manifest better health, relationships, wealth, and careers through his signature programs like Advance Law of Attraction™, Wealth Mastery, and Relationship Mastery—reaching over a million students worldwide.
                                </p>
                                <p>
                                    His bestsellers "Awaken the Leader In You" and "The Law of Attraction" (co-authored with Indu) have earned praise from leaders like Jack Canfield and Dr. John Demartini. Mitesh continues to innovate in coaching, training, and mindset transformation—empowering individuals and organizations to unlock their full potential.
                                </p>
                            </>
                        )}
                        <button
                            onClick={() => setIsDescriptionExpanded(!isDescriptionExpanded)}
                            className="text-sm font-medium text-foreground hover:underline flex items-center gap-1"
                        >
                            {isDescriptionExpanded ? 'View less' : 'View more'}
                            <span className={cn("transition-transform", isDescriptionExpanded ? "rotate-180" : "")}>^</span>
                        </button>
                    </div>
                </div>
            </main>

            {/* Chat Input */}
            <div className="p-4 max-w-3xl mx-auto w-full sticky bottom-0 bg-background/80 backdrop-blur-sm pb-8">
                <div className="relative">
                    <div className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground">
                        <Sparkles className="w-5 h-5" />
                    </div>
                    <Input
                        value={message}
                        onChange={(e) => setMessage(e.target.value)}
                        onKeyDown={(e) => {
                            if (e.key === 'Enter' && message.trim()) {
                                navigate('/chat', { state: { initialMessage: message } });
                            }
                        }}
                        placeholder="Ask Mitesh Khatri a question"
                        className="pl-12 pr-12 py-6 rounded-full shadow-sm border-muted-foreground/20 bg-muted/30 focus-visible:ring-1 focus-visible:ring-orange-500"
                    />
                    <Button
                        size="icon"
                        onClick={() => {
                            if (message.trim()) {
                                navigate('/chat', { state: { initialMessage: message } });
                            }
                        }}
                        className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full h-8 w-8 bg-muted text-muted-foreground hover:bg-orange-500 hover:text-white transition-colors"
                    >
                        <ArrowRight className="w-4 h-4" />
                    </Button>
                </div>
            </div>
        </div>
    );
};

export default TalkToDelphiPage;
