import { useState } from 'react';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Info, Quote, Image, Phone, Video } from 'lucide-react';
import { cn } from '@/lib/utils';

const ExperienceSettingsView = () => {
    const [initialMessage, setInitialMessage] = useState("Hey Platinum Magician, this is Mitesh AI, how can i help you?");
    const [noAnswerMessage, setNoAnswerMessage] = useState("I'm sorry, I don't have the answer to that right now. In the meantime, feel free to explore our website at https://www.miteshkhatri.com or let me know if there's anything else I can assist with!");

    // Experience State
    const [showCitations, setShowCitations] = useState(true);
    const [enableFileSending, setEnableFileSending] = useState(true);
    const [enableVoiceCalling, setEnableVoiceCalling] = useState(true);
    const [enableVideoCalling, setEnableVideoCalling] = useState(false);

    // Advanced Settings State
    const [showDisclaimer, setShowDisclaimer] = useState(true);
    const [disclaimerText, setDisclaimerText] = useState("This is an AI assistant based on Mitesh's teachings and content. Responses are generated by AI and do not replace personalized coaching or professional advice.");

    return (
        <div className="max-w-4xl mx-auto p-8 space-y-8">
            <div className="space-y-1">
                <h2 className="text-2xl font-semibold">Experience Settings</h2>
                <p className="text-muted-foreground">Configure how your Clone interacts with users.</p>
            </div>

            <div className="space-y-6">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-medium">Message Settings</h3>
                    <Info className="w-4 h-4 text-muted-foreground" />
                </div>

                <div className="space-y-8">
                    <div className="space-y-2">
                        <Label>Initial Message</Label>
                        <p className="text-sm text-muted-foreground">
                            This message will be used as your clone's first message in new conversations with users
                        </p>
                        <div className="relative">
                            <Textarea
                                value={initialMessage}
                                onChange={(e) => setInitialMessage(e.target.value)}
                                className="min-h-[100px] resize-none"
                                maxLength={400}
                            />
                            <span className={cn("absolute bottom-2 right-2 text-xs", initialMessage.length > 400 ? "text-red-500" : "text-muted-foreground")}>
                                {initialMessage.length}/400
                            </span>
                        </div>
                    </div>

                    <div className="space-y-2">
                        <Label>Message on No Answer</Label>
                        <p className="text-sm text-muted-foreground">
                            Your clone's response when it does not have enough data to answer the user's query.
                        </p>
                        <div className="relative">
                            <Textarea
                                value={noAnswerMessage}
                                onChange={(e) => setNoAnswerMessage(e.target.value)}
                                className="min-h-[120px] resize-none"
                                maxLength={400}
                            />
                            <span className={cn("absolute bottom-2 right-2 text-xs", noAnswerMessage.length > 400 ? "text-red-500" : "text-muted-foreground")}>
                                {noAnswerMessage.length}/400
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div className="space-y-6">
                <h3 className="text-lg font-medium">Experience</h3>

                <div className="border rounded-lg p-6 space-y-2">
                    <h4 className="font-medium">Messages before email capture</h4>
                    <p className="text-sm text-muted-foreground">
                        Set the number of messages before users are required to log in or provide their email
                    </p>
                    <button className="text-sm text-orange-500 hover:underline flex items-center gap-1">
                        Configure message limit →
                    </button>
                </div>

                <div className="border rounded-lg divide-y">
                    <div className="p-4 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-muted-foreground">
                                <Quote className="w-4 h-4" />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-base">Show Citations</Label>
                                <p className="text-sm text-muted-foreground">Permits users to view sources</p>
                            </div>
                        </div>
                        <Switch checked={showCitations} onCheckedChange={setShowCitations} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="p-4 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-muted-foreground">
                                <Image className="w-4 h-4" />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable File Sending</Label>
                                <p className="text-sm text-muted-foreground">Allow users to send images or files to your clone</p>
                            </div>
                        </div>
                        <Switch checked={enableFileSending} onCheckedChange={setEnableFileSending} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="p-4 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-muted-foreground">
                                <Phone className="w-4 h-4" />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable Voice Calling</Label>
                                <p className="text-sm text-muted-foreground">Allows users to call your clone. A voice must be uploaded.</p>
                            </div>
                        </div>
                        <Switch checked={enableVoiceCalling} onCheckedChange={setEnableVoiceCalling} className="data-[state=checked]:bg-orange-500" />
                    </div>

                    <div className="p-4 flex items-center justify-between">
                        <div className="flex items-center gap-4">
                            <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center text-muted-foreground">
                                <Video className="w-4 h-4" />
                            </div>
                            <div className="space-y-0.5">
                                <Label className="text-base">Enable Video Calling</Label>
                                <p className="text-sm text-muted-foreground">Allows users to video call your clone. A video avatar must be setup.</p>
                            </div>
                        </div>
                        <Switch checked={enableVideoCalling} onCheckedChange={setEnableVideoCalling} className="data-[state=checked]:bg-orange-500" />
                    </div>
                </div>
            </div>

            <div className="space-y-6">
                <div className="flex items-center gap-2">
                    <h3 className="text-lg font-medium">Advanced Settings</h3>
                    <Info className="w-4 h-4 text-muted-foreground" />
                </div>

                <div className="space-y-6">
                    <div className="space-y-4">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <Label className="text-base">Disclaimer</Label>
                                <span className="px-2 py-0.5 text-xs bg-muted text-muted-foreground rounded-full">Optional</span>
                            </div>
                            <Switch checked={showDisclaimer} onCheckedChange={setShowDisclaimer} className="data-[state=checked]:bg-orange-500" />
                        </div>
                        <p className="text-sm text-muted-foreground">
                            This banner appears at the top of the chat interface if specified.
                        </p>
                        {showDisclaimer && (
                            <div className="relative">
                                <Textarea
                                    value={disclaimerText}
                                    onChange={(e) => setDisclaimerText(e.target.value)}
                                    className="min-h-[100px] resize-none"
                                    maxLength={400}
                                />
                                <span className={cn("absolute bottom-2 right-2 text-xs", disclaimerText.length > 400 ? "text-red-500" : "text-muted-foreground")}>
                                    {disclaimerText.length}/400
                                </span>
                            </div>
                        )}
                    </div>

                    <div className="space-y-4 pt-4 border-t">
                        <div className="flex items-center gap-2">
                            <Label className="text-base">Disable your Talk Page</Label>
                            <span className="px-2 py-0.5 text-xs bg-red-100 text-red-600 rounded-full">Danger Zone</span>
                        </div>
                        <p className="text-sm text-muted-foreground">
                            Disabling your Talk Page will prevent all users from interacting with your clone. This action affects both new and existing users.
                        </p>
                        <Button variant="destructive" className="bg-red-100 text-red-600 hover:bg-red-200 border-none">
                            Disable Talk Page
                        </Button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ExperienceSettingsView;
